export const GET_TODAY = "GET_TODAY"
export const CALCULATE_INCREASE_RECOVERED = "CALCULATE_INCREASE_RECOVERED"


export const NEXT_FIVE_DAYS_CASES = "NEXT_FIVE_DAYS_CASES"
export const NEXT_FIVE_DAYS_DEATH = "NEXT_FIVE_DAYS_DEATH"
export const GET_DATES = "GET_DATES"
export const GET_PAST = "GET_PAST"
